config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :supers do
    resources :bookings
    member do
      put "like" => "supers#upvote"
      put "unlike" => "supers#downvote"
    end
  end
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :super
end

app/models/super.rb
class Super < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_one_attached :photo
  validates :name, presence: true, uniqueness: true
  acts_as_votable
  # validates :quote, presence: true
#   validates :location, :photo, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :supers
  has_many :bookings
  acts_as_voter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  # before_action :set_user, only: [:destroy, :create]
  before_action :set_super, only: [:new, :create]

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(super_id: params[:super_id].to_i)
    @booking.user = current_user
    if @booking.save
      redirect_to user_path(current_user)
     else
      render :new
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to user_path(current_user)
  end

  private

  def set_super
    @super = Super.find(params[:super_id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/supers_controller.rb
class SupersController < ApplicationController
  before_action :set_super, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  before_action :set_user, only: [:new, :create]

  def index
    if params[:superhero].present?
      if params[:superhero] == "true"
        @supers = Super.where(good: true).order(:cached_votes_up => :desc)
      else
        @supers = Super.where(good: false).order(:cached_votes_up => :desc)
      end
    else
      if params[:query].present?
        sql_query = " \
          supers.name @@ :query \
          OR supers.description @@ :query \
          OR supers.quote @@ :query \
          OR supers.location @@ :query \
        "
        @supers = Super.where(sql_query, query: "%#{params[:query]}%")
      else
        @supers = Super.all.order(:cached_votes_up => :desc)
      end
    end
  end

  def show
  end

  def new
    @super = Super.new
  end

  def edit
  end

  def update
    if @super.update(super_params)
      redirect_to @super, notice: 'Superhero was successfully updated.'
    else
      render :edit
    end
  end

  def create
    @super = Super.new(super_params)
    @super.user = current_user
    if @super.save
      redirect_to super_path(@super)
    else
      render :new
    end
  end

  def destroy
    @super.destroy
    redirect_to supers_path
  end

  def upvote
    @super = Super.find(params[:id])
    @super.upvote_from current_user
    @super.save
    # redirect_back fallback_location: supers_path
    redirect_to supers_path(@super, anchor: "superhero-#{@super.id}")
  end

  def downvote
    @super.downvote_from current_user
    redirect_back fallback_location: supers_path
  end

  private

  def set_user
    @user = current_user
  end

  def set_super
    @super = Super.find(params[:id])
  end

  def super_params
    params.require(:super).permit(:name, :location, :good, :photo, :description, :quote)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_booking_form.html.erb
<div class="row justify-content-center">
    <row class="col-lg-12">
      <h1>Add <%= @super.name %> to your team</h1>
      <%= simple_form_for [@super, Booking.new] do |f| %>
        <%= f.button :submit, 'Confirm', class: "btn-super-confirm" %>
      <% end %>
    </row>
</div>

app/views/bookings/_form.html.erb
<div class="row justify-content-center">
  <row class="col-lg-4">
    <%= simple_form_for [@booking, @super] do |f| %>
      <%= f.association :super %>
      <%= f.button :submit, class: "btn btn-primary" %>
    <% end %>
  </row>
</div>

app/views/bookings/new.html.erb
<%= render 'booking_form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SuperheroBnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="superhero-supervillain d-flex">
  <%= link_to supers_path(superhero: true) do %>
    <div class="panel hero d-flex justify-content-center" style="background-image: linear-gradient(rgba(255,69,0,0.2),rgba(255,69,0,0.4)), url(<%= asset_path("superheroes.jpg") %>);">
      <p class="text top-left btn-super-nav">Superheroes!</p>
      <p class="front-text align-self-center">Come and see all the universe's heroes!</p>
    </div>
  <% end %>

  <%= link_to supers_path(superhero: false) do %>
    <div class="panel villain d-flex justify-content-center" style="background-image: linear-gradient(rgba(5,15,77,0.4),rgba(5,15,77,0.4)), url(<%= asset_path("supervillain.jpg") %>);">
      <p class="text bottom-right btn-super-nav">Supervillains!</p>
      <p class="front-text align-self-center">Choose the dark side with the villains!</p>
    </div>
  <% end %>
  
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-super-bnb">


  <button class="navbar-toggler btn-super-nav" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="nav-item d-flex">
    <%= link_to "New Super!", new_super_path, class: "btn-super-nav" %>
    <%= link_to 'Heroes', supers_path(superhero: true), class: "btn-super-nav" %>
    <%= link_to 'Villains', supers_path(superhero: false), class: "btn-super-nav" %>
  </div>

  <div>
    <h1 class="super-title">Supers!</h1>
  </div>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <% if user_signed_in? %>

        <div class="nav-item dropdown">
          <%= image_tag "https://avatars2.githubusercontent.com/u/60719853?s=460&u=d6c47e5e47f08a8bd55e0f80c74e9ea86d0c47d8&v=4", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Profile", user_path(current_user), class: "btn-super-nav" %>
    <!--         <%= link_to "Create New Hero", new_super_path, class: "nav-link" %> -->
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "btn-super-nav" %>
          </div>
        </div>
      <% else %>
        <div class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "btn-super-nav" %>
        </div>
      <% end %>

  </div>
</div>

app/views/supers/_form.html.erb
<div class="row justify-content-center">
  <div class="form_container">
    <row class="col-lg-8">
    <%= simple_form_for @super do |f| %>
      <%= f.input :name %>
      <%= f.input :location %>
      <%= f.input :description %>
      <%= f.input :quote %>
      <%= f.input :photo, as: :file %>
      <%= f.collection_radio_buttons :good, [[true, 'Hero'], [false, 'Villain']], :first, :last %>
      <%= f.button :submit, class: "btn-super-confirm" %>
    <% end %>
  </row>
  </div>
</div>

app/views/supers/edit.html.erb
<%= render 'form' %>
<%= link_to"Back", super_path(@super) %>

app/views/supers/index.html.erb
<div class="container-index">
  <h1>Build your team!</h1>

  <form action="/supers" accept-charset="UTF-8" method="get">
    <div class="d-flex w-25">
      <input type="text" name="query" id="query" class="form-control-search" placeholder="Find your Superhero or Villain!">
      <input type="submit" name="commit" value="Search" class="btn-super-search" data-disable-with="Search">
    </div>
  </form>

  <div class="cards">
    <% @supers.each do |superhero| %>
      <% if superhero.photo.attached? %>

        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path superhero.photo.key %>')">
          <div>
            <p class="speech"><%= superhero.quote %></p>
          </div>
          <div class="link-box">
            <%= link_to super_path(superhero.id) do %>
              <h2><%= superhero.name %></h2>
            <% end %>
          </div>

          <%= link_to like_super_path(superhero), remote: true, class: "like", method: :put do %>
          <button type="button" class="btn btn-info" aria-label="Left Align">
            <span class="glyphicon glyphicon-thumbs-up glyphicon-align-center" aria-hidden="true"></span>
            <span class="badge" id="superhero-<%= superhero.id %>"><%= superhero.get_upvotes.size %></span>
          </button>
        <% end %>
        </div>

      <% else %>
        <div class="card-category">
          <div>
            <p class="speech"><%= superhero.quote %></p>
          </div>
          <div class="link-box">
            <%= link_to super_path(superhero.id) do %>
              <h2><%= superhero.name %></h2>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/supers/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', supers_path %> |

app/views/supers/show.html.erb
<div class="container-show">
  <div class="row"></div>

  <div class="container-super-image">
    <% if @super.photo.attached? %>
      <%= cl_image_tag @super.photo.key, width: 400, height: 500, crop: :fill %>
    <% else %>
      <%= image_tag 'superheroes.jpg', width: 400, height: 500 %>
    <% end %>
    <div>
      <% if @super.user == current_user %>
        <%= link_to 'Edit', edit_super_path(@super), class: "btn btn-super-edits" %>
        <%= link_to 'Delete', super_path(@super), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-super-edits" %>
      <% end %>
    </div>
  </div>

  <div class="container-super-card">

    <div class="container-super-infos">

      <div class="show-super-name">
        <h1> <%= @super.name %></h1>
      </div>

      <div class="show-super-location">
        <h3><%= @super.location %></h3>
      </div>
      <div class="show-super-good">
        <% if @super.good == true %>
        <h3>Hero</h3>
      <% else %>
        <h3>Villain</h3>
      <% end %>
      </div>

    </div>

    <div class="super-info-box">
      <p class="super-description-box"><%= @super.description %></p>
    </div>

    <button type="button" class="btn-super-nav" data-toggle="modal" data-target="#exampleModal">
      Add to team
    </button>
    <%= link_to 'Back', supers_path, class: "btn-super-nav"%>

  </div>

</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <%= render 'bookings/booking_form' %>
      </div>
    </div>
  </div>
</div>

app/views/users/_fight.html.erb
<h1>Your justice league defeats the evil justice league</h1>

app/views/users/show.html.erb
<div class="user-profile-info">
  <h1 class="main-header"> Here are your Lineups!</h1>
  <div class="user-rosters d-flex">
    <div class="hero-profile heroes">
      <h2 class="lineup-subheader">Your Justice League</h2>
      <% @user.bookings.each do |booking| %>
        <% if booking.super.good == true %>
          <div class="d-flex hero-individual">
            <div><%= cl_image_tag booking.super.photo.key, class: "profile-image" %></div>
            <div class="conten-box">
              <h2><%= link_to "#{booking.super.name}", super_path(booking.super_id)%></h2>
              <p class="hero-description"><%= booking.super.description %>
                <br>
                <%= link_to 'Delete', super_booking_path(booking.super, booking), class: "btn btn-warning", method: :delete, data: {confirm: "Are you sure?"} %>
              </p>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="user-center">
      <button type="button" class="btn-super-nav" data-toggle="modal" data-target="#exampleModal">
        FIGHT!
      </button>
    </div>
    <div class="hero-profile villains">
      <h2 class="lineup-subheader-evil">Your Evil Justice League</h2>
      <% @user.bookings.each do |booking| %>
        <% if booking.super.good == false %>
          <div class="d-flex hero-individual">
           <div><%= cl_image_tag booking.super.photo.key, class: "profile-image" %></div>
            <div class="conten-box">
              <h2><%= link_to "#{booking.super.name}", super_path(booking.super_id)%></h2>
              <p class="hero-description"><%= booking.super.description %>
                <br>
                <%= link_to 'Delete', super_booking_path(booking.super, booking), class: "btn btn-warning", method: :delete, data: {confirm: "Are you sure?"} %>
              </p>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <%= render 'users/fight' %>
      </div>
    </div>
  </div>
</div>